# Evaluation Dataset Configuration for Construction Agent
# This file contains the input queries and expected outputs for end-to-end evaluation

dataset:
  name: "agent_end_to_end_evaluation"
  description: "End-to-end evaluation for the Construction Agent, including expected final responses and tool calls."
  version: "1.0.0"
  created_date: "2025-06-15" # Updated to current date

# Input queries for the AI agent (these are the direct user queries)
inputs:
  - "How many square meters is Room A?"
  - "What's the area of the corridor in this plan?"
  - "Can you tell me the scale of Drawing 101?"
  - "Is this floor plan in 1:100 or something else?"
  - "Give me pipe details near the west wall."
  - "What's the material and diameter of the pipe at point B?"
  - "What's the scale and the area of Room 101?"
  - "What's the pipe length and the scale under it?"
  - "How big is the pipe?"
  - "Can you measure this?"
  - "Tell me everything about this location."
  - "Hello?"
  - "What is the size of region 5?"
  - "Where is the pipe connected in zone C?"
  - "What's the zoom level of this blueprint?"
  - "Show me the area of the main lobby."
  - "Scale of plan D-205 please."
  - "Info on water lines at 10,20 on Floor 3."
  - "What is the scale?"
  - "Area of Room 202 and pipe details at (50, 60)."
  - "What about pipes?"
  - "Who is the current Prime Minister?"
  - "Calculate the area of the breakroom."
  - "Give me the scale of that drawing."
  - "What are the properties of the pipe near the entrance?"
  - "How do I set up a server?"
  - "I need the area of the cafeteria and the scale of this document."
  - "What's the elevation here?"
  - "Show me pipe info at (100, 150, 10)."
  - "Can you help me understand construction permits?"

# Expected outputs from the AI agent (final responses and tool call details)
# Each item in this list corresponds to an input query by index.
expected_outputs:
  - Answer:
      final_response: "The area of Room A is 50 square meters."
      expected_tool_call:
        name: "measure_area"
        args:
          region: "Room A"

  - Answer:
      final_response: "To measure the area of the corridor, please specify which plan or drawing you are referring to."
      # No expected_tool_call as it leads to clarification

  - Answer:
      final_response: "The scale of Drawing 101 is 1:50."
      expected_tool_call:
        name: "get_scale"
        args:
          drawing: "Drawing 101"

  - Answer:
      final_response: "To determine the scale of the floor plan, please provide its specific drawing ID."
      # No expected_tool_call

  - Answer:
      final_response: "I need a more specific location for the pipe details, such as coordinates or a room number near the west wall."
      # No expected_tool_call

  - Answer:
      final_response: "The pipe at point B is made of PVC and has a diameter of 10 inches."
      expected_tool_call:
        name: "query_pipe_info"
        args:
          location: "point B"

  - Answer:
      final_response: "The area of Room 101 is 100 square meters. For the scale, please specify which drawing Room 101 is on, as 'Room 101' is not a drawing ID." # Combined response
      expected_tool_calls: # Changed to 'expected_tool_calls' for multiple
        - name: "get_scale"
          args:
            drawing: "Room 101" # This arg might be passed even if ambiguous
        - name: "measure_area"
          args:
            region: "Room 101"

  - Answer:
      final_response: "To get the pipe length, I need a specific location. To provide the scale, please specify which drawing you are referring to."
      # No expected_tool_call for this as both are ambiguous

  - Answer:
      final_response: "Please provide a specific location or identifier for the pipe you are asking about."
      # No expected_tool_call

  - Answer:
      final_response: "What specific area or object would you like me to measure?"
      # No expected_tool_call

  - Answer:
      final_response: "Please provide a more precise location (e.g., coordinates, room number) so I can retrieve relevant information."
      # No expected_tool_call

  - Answer:
      final_response: "Sorry, the query seems unfamiliar. I am a construction assistant and I can only help with construction related tasks."
      # No expected_tool_call

  - Answer:
      final_response: "The size of Region 5 is 250 square meters."
      expected_tool_call:
        name: "measure_area"
        args:
          region: "region 5"

  - Answer:
      final_response: "The pipe in zone C is connected to the main water line and leads to point X."
      expected_tool_call:
        name: "query_pipe_info"
        args:
          location: "zone C"

  - Answer:
      final_response: "To tell you the zoom level (scale) of the blueprint, please specify its ID."
      # No expected_tool_call

  - Answer:
      final_response: "The area of the main lobby is 500 square meters."
      expected_tool_call:
        name: "measure_area"
        args:
          region: "main lobby"

  - Answer:
      final_response: "The scale of plan D-205 is 1:75."
      expected_tool_call:
        name: "get_scale"
        args:
          drawing: "plan D-205"

  - Answer:
      final_response: "At coordinates (10,20) on Floor 3, the water line is 2-inch copper pipe."
      expected_tool_call:
        name: "query_pipe_info"
        args:
          location: "10,20 on Floor 3"

  - Answer:
      final_response: "Please specify which drawing or plan you would like to know the scale of."
      # No expected_tool_call

  - Answer:
      final_response: "The area of Room 202 is 120 square meters. The pipe at (50, 60) is a 4-inch steel pipe."
      expected_tool_calls: # Changed to 'expected_tool_calls' for multiple
        - name: "measure_area"
          args:
            region: "Room 202"
        - name: "query_pipe_info"
          args:
            location: "(50, 60)"

  - Answer:
      final_response: "Could you please specify what information you are looking for about pipes, and a location?"
      # No expected_tool_call

  - Answer:
      final_response: "Sorry, the query seems unfamiliar. I am a construction assistant and I can only help with construction related tasks."
      # No expected_tool_call

  - Answer:
      final_response: "The area of the breakroom is 80 square meters."
      expected_tool_call:
        name: "measure_area"
        args:
          region: "breakroom"

  - Answer:
      final_response: "Please specify which drawing you are referring to so I can provide its scale."
      # No expected_tool_call

  - Answer:
      final_response: "To provide the properties of the pipe, please give me a more precise location near the entrance."
      # No expected_tool_call

  - Answer:
      final_response: "Sorry, the query seems unfamiliar. I am a construction assistant and I can only help with construction related tasks."
      # No expected_tool_call

  - Answer:
      final_response: "The area of the cafeteria is 150 square meters. For the scale, please specify which document you mean."
      expected_tool_calls:
        - name: "measure_area"
          args:
            region: "cafeteria"
        - name: "get_scale"
          args:
            drawing: null # Agent might still call, but with null for ambiguous arg

  - Answer:
      final_response: "Sorry, the query seems unfamiliar. I am a construction assistant and I can only help with construction related tasks."
      # No expected_tool_call

  - Answer:
      final_response: "The pipe at (100, 150, 10) is a 6-inch steel pipe with a flow rate of 20 GPM."
      expected_tool_call:
        name: "query_pipe_info"
        args:
          location: "(100, 150, 10)"

  - Answer:
      final_response: "Sorry, the query seems unfamiliar. I am a construction assistant and I can only help with construction related tasks."
      # No expected_tool_call

# Output settings (as in your sample, though these are for local file saving, not LangSmith upload directly)
output:
  csv_filename: "agent_end_to_end_eval_ground_truth.csv"
  json_filename: "agent_end_to_end_eval_ground_truth.json"
  include_timestamp: true
  output_directory: "evaluation/datasets"